apiVersion: atlas.mongodb.com/v1
kind: AtlasDeployment
metadata:
  name: project-balabit-cluster01
  namespace: mongodb-atlas-system
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  projectRef:
    name: project-balabit
  deploymentSpec:
    autoScaling:
      compute:
        enabled: true
        scaleDownEnabled: true
    clusterType: REPLICASET
    name: prjbalabit-cluster01
    providerBackupEnabled: true
    paused: true
    providerSettings:
      instanceSizeName: M10
      providerName: GCP
    replicationSpecs:
      - numShards: 1
        regionsConfig:
          CENTRAL_US:
            analyticsNodes: 0
            electableNodes: 1
            priority: 6
            readOnlyNodes: 0
          US_EAST_4:
            analyticsNodes: 0
            electableNodes: 2
            priority: 7
            readOnlyNodes: 0
        zoneName: Zone 1